version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - database_url=postgres://postgres:postgres@postgres/postgres
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    command: bash -c "python src/main.py"
    depends_on:
      - postgres


  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
